Repository mask-dsn/mask-electron, pull requests merged in 2019-03, with the labels that each got.

#13 blockchain-starup
  app/components/Board.css
  app/components/Board.js
  app/main.dev.js
  app/reducers/board.js
  app/utils/blockchain.js
  app/utils/tracker.js
Labels: enhancement, please review

#15 readme
  README.md
Labels: enhancement, please review

#17 addPost
  app/utils/Post.js
Labels: don't merge, enhancement

#19 Post UI
  app/components/Board.js
  app/components/Postbox.css
  app/components/Postbox.js
  app/main.dev.js
  app/utils/Block.js
  app/utils/Chain.js
  app/utils/Post.js
  app/utils/blockchain.js
  app/utils/timestampUtil.js
Labels: enhancement, please review

#14 post-list-ui
  app/components/Board.js
  app/components/Counter.css
  app/components/Counter.js
  app/components/Feed.js
  app/components/Home.js
  app/components/Postbox.js
  app/components/css/Board.css
  app/components/css/Feed.css
  app/components/css/Home.css
  app/components/css/Postbox.css
  app/main.dev.js
  app/utils/Chain.js
  app/utils/Post.js
  app/utils/startup.js
  package.json
  yarn.lock
Labels: enhancement, please review

#23 scrollable-post-list
  app/components/Board.js
  app/components/Feed.js
  app/components/css/Board.css
  app/components/css/Postbox.css
  app/utils/timestampUtil.js
Labels: bug, please merge, please review

#24 Persist blockchain on shutdown
  .gitignore
  app/main.dev.js
  app/utils/Chain.js
  app/utils/blockchain.js
  app/utils/persistBlockchain.js
  app/utils/startup.js
  app/utils/tracker.js
Labels: enhancement, ready

#16 listen to updates in tracker
  app/main.dev.js
  app/utils/Chain.js
  app/utils/tracker.js
Labels: enhancement, please review

#28 search
  app/components/Board.js
  app/components/SearchBar.js
  package.json
  yarn.lock
Labels: enhancement, please review, ready

#29 image loading
  app/components/Board.js
  app/components/Feed.js
  app/components/css/Feed.css
  resources/image_loading.gif
Labels: enhancement, please merge, please review
